apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer-service
  name: producer-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
      - image: gagantk/producer-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: producer-service
        env:
        - name: KAFKA.SERVER.ADDRESS
          value: "kafka-cluster:9092"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer-service
  name: producer-service
  namespace: default
spec:
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: producer-service
  type: LoadBalancer