apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer-service
  name: consumer-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - image: gagantk/consumer-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: consumer-service
        ports:
        - containerPort: 9200
        env:
        - name: KAFKA.SERVER.ADDRESS
          value: "kafka-cluster:9092"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer-service
  name: consumer-service
  namespace: default
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: consumer-service
  type: LoadBalancer